### ISSUE TITLE
Support to deployment multiple clusters by using the same etcd cluster

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb-operator#124]
## Backgroud

The upstream already supports [`--store-key-prefix`](https://github.com/GreptimeTeam/greptimedb/pull/2988/files) in metasrv. We can provide the `StoreKeyPrefix` in the Meta field to support creating multiple clusters using the same etcd cluster.

**Comment by daviderli614** [comment]
https://github.com/GreptimeTeam/greptimedb-operator/pull/127
