### ISSUE TITLE
CRD defaulting and validation should not be placed in the controller

### ISSUE THREAD

**Issue by airycanon** [GreptimeTeam/greptimedb-operator#152]
CRD defaulting and validation should not be placed in the controller, but rather in the admission webhook.

Benefits:
* Users can receive clear and specific error messages when validation fails.
* If validation fails, it won't trigger the controller's reconcile, avoiding unnecessary resource consumption.

**Comment by zyy17** [comment]
IMO, to keep the operator deployment simple, adding the admission webhook should be **optional** for setting default value and validation.

Without admission webhook, control can still can set the default value and validation. If the resource fails the validation, the controller will stop the reconcile until the user modifies it to the correct value.

**Comment by airycanon** [comment]
> IMO, to keep the operator deployment simple, adding the admission webhook should be **optional** for setting default value and validation.
> 
> Without admission webhook, control can still can set the default value and validation. If the resource fails the validation, the controller will stop the reconcile until the user modifies it to the correct value.

I agree that the admission webhook is optional, but doing validation in the controller has a significant drawback: users won't receive immediate feedback when they submit incorrect fields. They would have to investigate the controller logs to troubleshoot the issue, which can be inconvenient and time-consuming.

**Comment by zyy17** [comment]
@airycanon Sorry for not getting back to you sooner. 

You're right, and we can take the admission webhook as an enhancement. We can keep track of it. I created the new issue #153. If you are interested in the feature, feel free to contribute to it.
